[workspace]
members = [
    "pa-wrapper",
    "pa-bin",
    "pa-bench-types",
    "pa-bench",
]
# 'cargo run' runs 'pa-bench', not 'pa-bin'.
default-members = ["pa-bench"]
resolver = "2"

[profile.release]
lto = "thin"
incremental = true
# True can slow things down.
debug = true
strip = false
