[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "^4.0", features = ["derive"] }
libc = "^0.2"
serde_json = "^1.0"
core-lib = { git = "https://github.com/pairwise-alignment/core-lib" }
parse_duration = "*"
itertools = "*"
